Odds:
  sport: basketball_nba
  bookmakers:
    - betmgm
    - betrivers
    - betparx
    - betonlineag
    - betus
    - bovada
    - draftkings
    - fanduel
    - fliff
    - lowvig
    - mybookieag
    - williamhill_us
    - wynnbet
    - espnbet
    - sisportsbook
    - hardrockbet
    - tipico_us
    - pinnacle
    - windcreek
    - superbook
  markets: h2h
  odds_format: decimal

Date:
  start_date: "2021-05-09T05:35:00Z"  # "2020-12-20T00:00:00Z"
  end_date: "2021-07-21T12:00:00Z"
  step: 10  # minutes

Season:
  season: "2020-2021"
  start: "2020-12-22T00:00:00Z"

