Odds:
  sport: americanfootball_nfl
  bookmakers:
    - betmgm
    - bovada
    - draftkings
    - fanduel
    - mybookieag
    - williamhill_us
    - espnbet
    - hardrockbet
    - tipico_us
    - pinnacle
  markets: h2h
  odds_format: decimal

Date:
  start_date: "2020-09-02T00:00:00Z"
  end_date: "2021-02-08T12:00:00Z"
  step: 10  # minutes

Season:
  season: "2020-2021"
  start: "2020-09-010T00:00:00Z"

