Odds:
  sport: soccer_epl
  bookmakers:
    - betmgm
    - bovada
    - draftkings
    - fanduel
    - mybookieag
    - williamhill_us
    - espnbet
    - hardrockbet
    - tipico_us
    - pinnacle
  markets: h2h
  odds_format: decimal

Date:
  start_date: "2021-08-06T00:00:00Z"
  end_date: "2022-05-23T00:00:00Z"
  step: 10  # minutes

Season:
  season: "2021-2022"
  season_start: "2021-08-13T00:00:00Z"