Odds:
  sport: basketball_nba
  bookmakers:
    - betmgm
    - betrivers
    - betparx
    - betonlineag
    - betus
    - bovada
    - draftkings
    - fanduel
    - fliff
    - lowvig
    - mybookieag
    - williamhill_us
    - wynnbet
    - espnbet
    - sisportsbook
    - hardrockbet
    - tipico_us
    - pinnacle
    - windcreek
    - superbook
  markets: h2h
  odds_format: decimal

Date:
  start_date: "2021-10-17T00:00:00Z"
  end_date: "2022-06-17T12:00:00Z"
  step: 10  # minutes

Season:
  season: "2021-2022"
  start: "2021-10-19T00:00:00Z"

