Odds:
  sport: americanfootball_nfl
  bookmakers:
    - betmgm
    - bovada
    - draftkings
    - fanduel
    - mybookieag
    - williamhill_us
    - espnbet
    - hardrockbet
    - tipico_us
    - pinnacle
  markets: h2h
  odds_format: decimal

Date:
  start_date: "2022-12-06T17:00:00Z"  # "2022-09-01T00:00:00Z"
  end_date: "2023-02-13T12:00:00Z"
  step: 10  # minutes

Season:
  season: "2022-2023"
  start: "2022-09-08T00:00:00Z"

