Odds:
  sport: basketball_nba
  bookmakers:
    - betmgm
    - betrivers
    - betparx
    - betonlineag
    - betus
    - bovada
    - draftkings
    - fanduel
    - fliff
    - lowvig
    - mybookieag
    - williamhill_us
    - wynnbet
    - espnbet
    - sisportsbook
    - hardrockbet
    - tipico_us
    - pinnacle
    - windcreek
    - superbook
  markets: h2h
  odds_format: decimal

Date:
  start_date: "2022-10-16T00:00:00Z"
  end_date: "2023-06-13T12:00:00Z"
  step: 10  # minutes

Season:
  season: "2022-2023"
  start: "2022-10-18T00:00:00Z"

