Odds:
  sport: americanfootball_nfl
  bookmakers:
    - betmgm
    - bovada
    - draftkings
    - fanduel
    - mybookieag
    - williamhill_us
    - espnbet
    - hardrockbet
    - tipico_us
    - pinnacle
  markets: h2h
  odds_format: decimal

Date:
  start_date: "2023-09-01T00:00:00Z"
  end_date: "2024-02-12T00:00:00Z"
  step: 10  # minutes

Season:
  season: "2023-2024"
  start: "2023-09-07T00:00:00Z"

